config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  get 'home/index'

  resources :projects

  root 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :status_id, :description)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  def create
    @status = Status.new(status_params)

    if @status.save
      redirect_to @status, notice: 'Status was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /statuses/1
  def update
    if @status.update(status_params)
      redirect_to @status, notice: 'Status was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /statuses/1
  def destroy
    if @status.project.count != 0
      redirect_to statuses_url, alert: 'Cannot destroy statuses that are assigned.'
      return
    end
    @status.destroy
    redirect_to statuses_url, notice: 'Status was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def status_params
      params.require(:status).permit(:name, :color, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_header.html.erb
<header>
  <section>
    <h1><%= link_to 'UX Project Status Dashboard', root_path %></h1>
  </section>
</header>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/home/index.html.erb
<section class="wrapper">
<ul class="project-list">
  <% Project.all.each do |p| %>
    <li class="block" style="background-color:<%= p.status.color %>">
      <%= link_to p do %>
        <div class="project-list-item">
          <%= p.name %>: <%= p.status.name %>
          <div>
          <% end %>
    </li>
  <% end %>
</ul>
</section>
<section>
  <hr>
  <%=link_to 'New Project', new_project_path, class: 'button'%>
  <%=link_to '(Statuses)', statuses_path%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "header" -%>
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :status do %>
    <span>(<%= link_to 'status list', statuses_path %>)</span>
    <%= f.collection_select :status_id, Status.order(:name), :id, :name %>
  <% end %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<section>
  <h2>Editing Project</h2>

  <%= render 'form' %>

  <hr>
  <%= link_to 'Cancel', @project, class: 'button' %>
</section>

app/views/projects/index.html.erb
<section>
<h1>Project Dashboard</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td style="background-color:<%= project.status.color %>"><%= project.status.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %> |
        <%= link_to 'Edit', edit_project_path(project) %> |
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
</section>

app/views/projects/new.html.erb
<section>
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</section>

app/views/projects/show.html.erb
<section>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Status:</strong>
  <% if @project.status %>
    <span style="background-color:<%=@project.status.color%>">
      <%= @project.status.name %>
    </span>
  <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project), class: 'button' %> |
<%= link_to 'Back', root_path, class: 'button' %>
</section>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :color %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<section>
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>
</section>

app/views/statuses/index.html.erb
<section>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Description</th>
      <th>Assigned Projects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.name %></td>
        <td style="background-color:<%= status.color %>;"><%= status.color %></td>
        <td><%= status.description %></td>
        <td><%= status.project.count %></td>
        <td><%= link_to 'Details', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path, class: 'button' %>
</section>

app/views/statuses/new.html.erb
<section>
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</section>

app/views/statuses/show.html.erb
<section>
<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Color:</strong>
  <span style="background-color:<%=@status.color%>">
    <%= @status.color %>
  </span>
</p>

<p>
  <strong>Description:</strong>
  <%= @status.description %>
</p>

<h2>Associated Projects</h2>
<p>
<ul>
  <% @status.project.each do |p| %>
    <li><%= link_to p.name, p%></li>
  <% end %>
</ul>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>
</section>